#!/usr/bin/env python3
"""Generate the portfolio's browser-release summary from published route metadata."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SHA = re.compile(r"[0-9a-f]{40}\Z")
REPOSITORY = re.compile(r"[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+\Z")
SLUG = re.compile(r"[a-z0-9]+(?:-[a-z0-9]+)*\Z")


def validate_publication(path: Path, data: object) -> dict[str, str | int]:
    if not isinstance(data, dict) or set(data) != {
        "publisher", "sourceRepository", "sourceCommit", "sourceRunId"
    }:
        raise ValueError(f"{path}: invalid publication fields")
    repository = data["sourceRepository"]
    commit = data["sourceCommit"]
    run_id = data["sourceRunId"]
    if data["publisher"] != "pages":
        raise ValueError(f"{path}: publisher must be pages")
    if not isinstance(repository, str) or not REPOSITORY.fullmatch(repository):
        raise ValueError(f"{path}: invalid source repository")
    if not isinstance(commit, str) or not SHA.fullmatch(commit):
        raise ValueError(f"{path}: invalid source commit")
    if type(run_id) is not int or run_id <= 0:
        raise ValueError(f"{path}: invalid source run ID")
    return data


def render(root: Path, replacement: tuple[str, dict[str, str | int]] | None = None) -> str:
    publications: dict[str, dict[str, str | int]] = {}
    public = root / "public"
    for path in sorted(public.glob("*/publication.json")):
        slug = path.parent.name
        if not SLUG.fullmatch(slug):
            raise ValueError(f"{path}: invalid route slug")
        if replacement is not None and slug == replacement[0]:
            continue
        publications[slug] = validate_publication(path, json.loads(path.read_text(encoding="utf-8")))
    if replacement is not None:
        slug, publication = replacement
        if not SLUG.fullmatch(slug):
            raise ValueError(f"invalid route slug: {slug}")
        publications[slug] = validate_publication(public / slug / "publication.json", publication)

    lines = [
        "// Generated by tools/sync_wasm_publications.py. Do not edit by hand.",
        "",
        "export interface WasmPublication {",
        "  sourceRepository: string;",
        "  sourceCommit: string;",
        "  sourceRunId: number;",
        "}",
        "",
        "const publications: Record<string, WasmPublication> = {",
    ]
    for slug, publication in sorted(publications.items()):
        key = slug if re.fullmatch(r"[A-Za-z_$][A-Za-z0-9_$]*", slug) else json.dumps(slug)
        lines.extend(
            [
                f"  {key}: {{",
                f"    sourceRepository: {json.dumps(publication['sourceRepository'])},",
                f"    sourceCommit: {json.dumps(publication['sourceCommit'])},",
                f"    sourceRunId: {publication['sourceRunId']},",
                "  },",
            ]
        )
    lines.extend(
        [
            "};",
            "",
            "export function wasmPublicationFor(slug: string): WasmPublication | undefined {",
            "  return publications[slug];",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def output_path(root: Path) -> Path:
    return root / "src" / "data" / "wasm-publications.generated.ts"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="refuse if the release summary is stale")
    args = parser.parse_args()
    try:
        rendered = render(ROOT)
    except (OSError, ValueError, json.JSONDecodeError) as error:
        parser.exit(2, f"browser publications: REFUSED: {error}\n")
    target = output_path(ROOT)
    if args.check:
        if not target.is_file() or target.read_text(encoding="utf-8") != rendered:
            parser.exit(1, "browser publications: stale release summary\n")
        print("browser publications: current")
        return 0
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(rendered, encoding="utf-8")
    print(f"browser publications: wrote {target.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
