#!/usr/bin/env python3
"""Generate the portfolio's feature-state snapshot from project-state registries."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path


PROJECT_PATHS = {
    "benefactor": "benefactor",
    "sunbright": "sunbright",
    "zelda3d": "zelda3d",
    "xmen2": "pc/xmen2",
    "lf2-port": "pc/lf2",
    "tomba2-engine": "psx/Tomba2Engine",
    "crash-bash": "psx/crashbash",
    "gears1": "x360/gears1",
    "psxport": "psx/psxport",
    "lucent": "lucent",
    "alchemy": "shared/alchemy",
    "port-assets": "shared/port-assets",
    "pinest": "pinest",
    "node-gtk-vte": "node-gtk-vte",
    "re-harness": "shared/re-harness",
    "wails-dbman": "wails-dbman",
    "wails-cast": "wails-cast",
    "wails-cast-remote": "wails-cast-remote",
    "fedora-kde-steamdeck": "fedora-kde-steamdeck",
    "prismlauncher": "PrismLauncher",
    "minecraft-supermarket": "minecraft",
    "setsail": "wiiu/setsail",
}

VALID_STATES = {"verified", "partial", "blocked", "missing"}
# A state row's stable ID: numbered (S12, S3a) or named with a project prefix
# (ST-APPIMAGE). The header row's plain "ID" matches neither.
STATE_ROW = re.compile(r"^\|\s*(?:S\d+[a-z]?|[A-Z][A-Z0-9]*(?:-[A-Z0-9]+)+)\s*\|")
DETAIL_HEADING = re.compile(r"^## (S\d+[a-z]?)\s+[—-]\s+(.+)$", re.MULTILINE)
DETAIL_STATUS = re.compile(r"^Status:\s*`?(verified|partial|blocked|missing)`?\s*$", re.MULTILINE)
COMPARISON_BASELINE_HEADING = re.compile(r"^## Comparison baseline\s*$", re.MULTILINE)
COMPARISON_BASELINE_INLINE = re.compile(r"^Comparison baseline:\s*(.+)$", re.MULTILINE)
SECOND_LEVEL_HEADING = re.compile(r"^##\s+", re.MULTILINE)


@dataclass(frozen=True)
class Feature:
    source_id: str
    label: str
    state: str


def parse_table(text: str, path: Path) -> list[Feature]:
    features: list[Feature] = []
    for line in text.splitlines():
        if not STATE_ROW.match(line):
            continue
        cells = [cell.strip() for cell in line.strip().strip("|").split("|")]
        if len(cells) == 5:
            source_id, label, state, _dependencies, _goals = cells
        elif len(cells) == 4:
            source_id, label, state, _evidence = cells
        else:
            raise ValueError(f"{path}: state row must contain four or five cells: {line}")
        if state not in VALID_STATES:
            raise ValueError(f"{path}: {source_id} has unsupported state {state!r}")
        features.append(Feature(source_id, label, state))
    return features


def parse_detail_inventory(text: str, path: Path) -> list[Feature]:
    matches = list(DETAIL_HEADING.finditer(text))
    features: list[Feature] = []
    for index, match in enumerate(matches):
        end = matches[index + 1].start() if index + 1 < len(matches) else len(text)
        detail = text[match.end() : end]
        status = DETAIL_STATUS.search(detail)
        if status:
            features.append(Feature(match.group(1), match.group(2).strip(), status.group(1)))
    if not features:
        raise ValueError(f"{path}: no state table or status-bearing S detail sections found")
    return features


def parse_features(path: Path) -> list[Feature]:
    if not path.is_file():
        raise FileNotFoundError(f"required project state does not exist: {path}")
    text = path.read_text(encoding="utf-8")
    features = parse_table(text, path)
    return features or parse_detail_inventory(text, path)


def parse_comparison_baseline(path: Path) -> str:
    text = path.read_text(encoding="utf-8")
    heading = COMPARISON_BASELINE_HEADING.search(text)
    if not heading:
        inline = COMPARISON_BASELINE_INLINE.search(text)
        if inline:
            return plain_baseline(inline.group(1))
        raise ValueError(f"{path}: required Comparison baseline section is missing")
    next_heading = SECOND_LEVEL_HEADING.search(text, heading.end())
    section_end = next_heading.start() if next_heading else len(text)
    first_paragraph = text[heading.end() : section_end].strip().split("\n\n", 1)[0]
    baseline = plain_baseline(first_paragraph)
    if not baseline:
        raise ValueError(f"{path}: Comparison baseline section is empty")
    return baseline


def plain_baseline(value: str) -> str:
    text = re.sub(r"\[([^]]+)\]\([^)]+\)", r"\1", value)
    return re.sub(r"\s+", " ", text.replace("*", "").replace("`", "")).strip()


def typescript_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def render(workspace_root: Path) -> tuple[str, int]:
    project_data: list[tuple[str, list[Feature], str]] = []
    total = 0
    for slug, relative_path in PROJECT_PATHS.items():
        state_path = workspace_root / relative_path / "docs" / "project-state.md"
        features = parse_features(state_path)
        project_data.append((slug, features, parse_comparison_baseline(state_path)))
        total += len(features)

    lines = [
        "// Generated by tools/sync_project_features.py. Do not edit by hand.",
        "",
        'export type ProjectFeatureState = "verified" | "partial" | "blocked" | "missing";',
        "",
        "export interface ProjectFeature {",
        "  sourceId: string;",
        "  label: string;",
        "  state: ProjectFeatureState;",
        "}",
        "",
        "const comparisonBaselinesByProject = {",
    ]
    for slug, _features, comparison_baseline in project_data:
        if comparison_baseline:
            lines.append(
                f"  {typescript_string(slug)}: {typescript_string(comparison_baseline)},"
            )
    lines.extend(
        [
            "} as const satisfies Record<string, string>;",
            "",
        "const featuresByProject = {",
        ]
    )
    for slug, features, _comparison_baseline in project_data:
        lines.append(f"  {typescript_string(slug)}: [")
        for feature in features:
            lines.extend(
                [
                    "    {",
                    f"      sourceId: {typescript_string(feature.source_id)},",
                    f"      label: {typescript_string(feature.label)},",
                    f"      state: {typescript_string(feature.state)},",
                    "    },",
                ]
            )
        lines.append("  ],")
    lines.extend(
        [
            "} as const satisfies Record<string, readonly ProjectFeature[]>;",
            "",
            "export type ProjectSlug = keyof typeof featuresByProject;",
            "",
            "export function featuresFor(slug: ProjectSlug): readonly ProjectFeature[] {",
            "  return featuresByProject[slug];",
            "}",
            "",
            "export function comparisonBaselineFor(slug: ProjectSlug): string {",
            "  return comparisonBaselinesByProject[slug];",
            "}",
            "",
        ]
    )
    return "\n".join(lines), total


def format_typescript(portfolio_root: Path, source: str, output_path: Path) -> str:
    formatter = portfolio_root / "node_modules" / ".bin" / "oxfmt"
    if not formatter.is_file():
        raise FileNotFoundError(f"required formatter does not exist: {formatter}")
    completed = subprocess.run(
        [str(formatter), f"--stdin-filepath={output_path}"],
        input=source,
        text=True,
        capture_output=True,
        check=False,
    )
    if completed.returncode != 0:
        detail = completed.stderr.strip() or completed.stdout.strip() or "no formatter output"
        raise ValueError(f"oxfmt failed: {detail}")
    return completed.stdout


def main() -> int:
    script_path = Path(__file__).resolve()
    portfolio_root = script_path.parent.parent
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--workspace-root",
        type=Path,
        default=portfolio_root.parent,
        help="workspace containing the project repositories (default: portfolio parent)",
    )
    parser.add_argument("--check", action="store_true", help="refuse if the snapshot is stale")
    args = parser.parse_args()

    output_path = portfolio_root / "src" / "data" / "project-features.generated.ts"
    try:
        rendered, feature_count = render(args.workspace_root.resolve())
        rendered = format_typescript(portfolio_root, rendered, output_path)
    except (FileNotFoundError, ValueError) as error:
        print(f"project features: REFUSED: {error}")
        return 2

    if args.check:
        if not output_path.is_file():
            print(f"project features: REFUSED: generated snapshot does not exist: {output_path}")
            return 2
        if output_path.read_text(encoding="utf-8") != rendered:
            print(
                f"project features: stale snapshot; checked {len(PROJECT_PATHS)} projects and "
                f"{feature_count} features"
            )
            return 1
        print(
            f"project features: current; checked {len(PROJECT_PATHS)} projects and "
            f"{feature_count} features"
        )
        return 0

    output_path.write_text(rendered, encoding="utf-8")
    print(
        f"project features: wrote {feature_count} features from {len(PROJECT_PATHS)} projects "
        f"to {output_path.relative_to(portfolio_root)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
