// Generated by tools/sync_project_features.py. Do not edit by hand.

export type ProjectFeatureState = "verified" | "partial" | "blocked" | "missing";

export interface ProjectFeature {
  sourceId: string;
  label: string;
  state: ProjectFeatureState;
}

const comparisonBaselinesByProject = {
  benefactor:
    "The user-facing baseline is the unmodified 1994 Amiga release under a conventional emulator: 320-pixel presentation, original controls and jump behavior, password flow, floppy timing, and Amiga startup.",
  sunbright:
    "The user-visible baseline is the unmodified NTSC-U GameCube release (GMSE01) running on original hardware or Dolphin with console execution, GX rendering, 4:3 framing, and normally 30 Hz presentation. The repository's former gameplay executor is absent; Sunbright currently has no gameplay executable while its shared runtime executor is missing.",
  zelda3d:
    "The baseline is the unmodified Nintendo 3DS releases of Ocarina of Time 3D and Majora's Mask 3D running on original hardware or through Azahar. Zelda3D's intended difference is one lawful native-PC experience that consumes the player's own remake assets while reproducing each remake's presentation and game-specific behavior outside a 3DS emulator.",
  xmen2:
    "The baseline is the unmodified 2005 Windows PC release of X-Men Legends II running on Windows or through Wine, with its original Direct3D 8 renderer, PC control defaults, prompts, settings, loading, and save flow. The port's intended differences are Wine-free native execution and a modern native-PC presentation, controller, settings, packaging, and diagnostics experience without changing the game.",
  "lf2-port":
    "The user-facing baseline is the unmodified Windows release of Little Fighter 2 v2.0a running on Windows or through Wine: fixed-resolution 4:3 DirectDraw, original keyboard/joystick configuration, and manual game-file setup.",
  "tomba2-engine":
    "The external baseline is the unmodified PlayStation releases of Tomba! and Tomba! 2 on original hardware or a trusted emulator. The immediate migration baseline is this repository's pre-migration native/offline-translated hybrid, whose remaining guest code was emitted offline and compiled into each product. The intended products retain title-native ownership while replacing that generated execution with runtime translation by psxport Lightrec.",
  "crash-bash":
    "The baseline is the unmodified USA PlayStation release of Crash Bash running on original hardware or through a PS1 emulator, with retail game modes, a 4:3 camera, 30 Hz presentation, and console CPU execution. The intended product authenticates the user's game image, executes selected behavior in native title owners, dynamically translates all remaining MIPS through psxport's pinned Lightrec revision, widens the camera, and adds 60 Hz interpolated presentation without accelerating simulation.",
  gears1: "retail Xbox 360 Gears titles running in an emulator.",
  psxport:
    "The baseline is the previous native PSX host framework with no usable product CPU executor. The tree now has a Linux x86-64 Lightrec execution path; the intended complete delta remains a dynarec-default Lightrec/native hybrid that executes authenticated user images at runtime and retains the existing native device, rendering, audio, input, HLE, and enhancement owners.",
  lucent:
    "The baseline is each native application independently reimplementing logging, configuration, user-data paths, local HTTP transport, safe archive import, and touch routing. Lucent provides those title-neutral runtime capabilities once, with bounded behavior and tested ownership boundaries.",
  alchemy:
    "The baseline is every Alchemy-engine game port carrying its own container decoders, archive tools, asset viewers, controller glue, and eventually title-local native engine replacements. This repository already provides measured shared libraries and tools, but no gameplay product currently links and exercises them as its engine boundary.",
  "port-assets":
    "The baseline is every port drawing or sourcing its own inconsistent controller, keyboard, device, and touch prompts. port-assets provides one original, scalable, target-size-checked visual language that consumers can label and render for their actual bindings.",
  pinest:
    "The baseline is operating a pi coding-agent session only from the host terminal, with no authenticated remote browser or phone control and no project-owned durable session registry. PiNest adds private remote session creation, observation, input, interruption, resume, discovery, and mobile delivery for one owner.",
  "node-gtk-vte":
    "The baseline is writing and maintaining a compiled native addon, or embedding a browser terminal, to place a remotely driven terminal inside a Linux desktop UI. node-gtk-vte exposes GTK 3, VTE 2.91, and GObject directly to Bun through FFI, including the widget, byte transport, composition, and lifetime seams applications need.",
  "re-harness":
    "The baseline is duplicated user-maintained instructions, skills, and command-line tools scattered across individual agent homes and project copies. re-harness makes one portable repository the authority, installs relative discovery links for supported agents, and verifies both successful and refused behavior.",
  "wails-dbman":
    "The baseline is switching between separate vendor-specific database clients and rebuilding connection, query, object-inspection, and workspace context for each engine. DBMan intends one native desktop workbench for SQL Server, PostgreSQL, and MySQL with persistent connections, tabs, exploration, editing, results, and search.",
  "wails-cast":
    "The baseline is manually combining local media browsing, download/extraction tools, transcoding, subtitle utilities, and a separate Chromecast controller. Wails Cast intends one desktop workflow for library management, media preparation, subtitles, casting, durable background work, and authenticated companion control.",
  "wails-cast-remote":
    "The baseline is returning to the Wails Cast desktop for every library, track-selection, subtitle, and transport action. WailsCast Remote intends the same authenticated workflow from Android and iOS, including discovery, pre-play choices, live controls, subtitle translation, and synchronized settings.",
  "fedora-kde-steamdeck":
    "The baseline is a stock Fedora KDE desktop session where Steam and Gamescope are launched and exited manually. This project intends a reversible SteamOS-like session choice that enters fullscreen Steam Gamepad UI, logs the run, returns cleanly to Plasma, and can be completely uninstalled.",
  prismlauncher:
    "The comparison baseline is upstream Prism Launcher at this fork's imported upstream checkpoint (3d01e09fc). S003-S006 add automatic local-network instance import, while S011 changes the selected-instance desktop shortcut workflow. The other state items describe retained upstream launcher capabilities whose current evidence is tracked independently. S012 and S013 add fork-specific maintenance and an optional native-package migration path. S014 tracks the fork's release packages across Linux and Apple Silicon macOS. S015 adds LAN updates for an existing instance in addition to creating a copy.",
  "minecraft-supermarket":
    "The previous milestone-customer-delivery-fixed Supermarket modpack release, which generated a smaller market settlement with checkout and delivery play but did not yet place the expanded city inside a surrounding sakura forest or provide the current full-height shelving and raised angled produce displays. Vanilla Minecraft supplies none of the supermarket gameplay.",
  setsail:
    "Baseline: playing Wind Waker HD in upstream Cemu. A player installs the Cemu AppImage, adds their WUX to a game list, optionally installs community graphic packs (WindWakerHD_Resolution, _Contrasty, _Shadows, _NoSSAO, _LODBias, _Anisotropic, _RemoveHUD, _PictoBox, _IntelFixes, _FPSSlowdownFix), and plays at the title's 30 Hz presentation rate. No 60 fps pack exists for this title. Each item below states its difference from that baseline.",
} as const satisfies Record<string, string>;

const featuresByProject = {
  benefactor: [
    {
      sourceId: "S001",
      label:
        "The complete game boots, transitions among all runtime images, and plays all 60 levels through the intended product",
      state: "partial",
    },
    {
      sourceId: "S002",
      label: "Native pause/options apply and persist modern settings in game",
      state: "partial",
    },
    {
      sourceId: "S003",
      label:
        "Keyboard, hot-pluggable controllers, touch, rebinding, and alternate controls share logical actions",
      state: "partial",
    },
    {
      sourceId: "S004",
      label: "Android provides no-terminal disk setup without packaged game assets",
      state: "verified",
    },
    {
      sourceId: "S005",
      label:
        "Native owners plus `shared/amigaport` execute every non-native 68000 path directly from authenticated runtime images",
      state: "partial",
    },
    {
      sourceId: "S006",
      label:
        "The working static recomp provides independent behavioral comparison for the shipping interpreter",
      state: "partial",
    },
    {
      sourceId: "S007",
      label:
        "Turbo, hyper, and hold-to-fast-forward change gameplay pace while audio remains at normal speed",
      state: "partial",
    },
    {
      sourceId: "S008",
      label:
        "Optional platformer physics provides variable jump, air control, momentum, and tunable motion while classic physics remains",
      state: "partial",
    },
    {
      sourceId: "S009",
      label: "A 60-level selector, completion progress, and locks replace password entry",
      state: "partial",
    },
    {
      sourceId: "S010",
      label:
        "Faithful, native software, and Vulkan renderers provide selectable lighting and shadow effects",
      state: "partial",
    },
    {
      sourceId: "S011",
      label:
        "16:9, 21:9, and live-window widescreen reveal additional simulated world rather than stretching",
      state: "partial",
    },
    {
      sourceId: "S012",
      label: "Native boot and disk/decompression owners remove Amiga startup and floppy waits",
      state: "partial",
    },
    {
      sourceId: "S013",
      label: "Free camera pans in real time or while paused",
      state: "partial",
    },
    {
      sourceId: "S014",
      label: "Easy, Normal, and Hard selection is restored in the main menu",
      state: "partial",
    },
    {
      sourceId: "S015",
      label: "Skip intro, unlock all levels, and reduced/disabled fall damage are configurable",
      state: "partial",
    },
    {
      sourceId: "S016",
      label: "Pickup and interaction reach can be extended independently of control scheme",
      state: "partial",
    },
    {
      sourceId: "S017",
      label:
        "Savestates, direct level entry, headless driving, profiling, and runtime probes support development",
      state: "partial",
    },
    {
      sourceId: "S018",
      label: "Player-facing save slots provide names, timestamps, and screenshot previews",
      state: "missing",
    },
    {
      sourceId: "S019",
      label: "Hold-to-rewind restores recent states from a bounded history",
      state: "missing",
    },
    {
      sourceId: "S020",
      label:
        "`shared/amigaport` supplies complete 68000 PC/SR/exception/cycle state and a maintained interpreter owner",
      state: "partial",
    },
    {
      sourceId: "S021",
      label:
        "Image-generation-aware execution, overrides, and scoped original calls work across all four address-reusing images",
      state: "partial",
    },
    {
      sourceId: "S022",
      label:
        "Gameplay uses one shared interpreter CPU owner and contains no generated/static execution or direct diagnostic-emulator dependency",
      state: "partial",
    },
    {
      sourceId: "S023",
      label:
        "Representative interactive gameplay conforms and meets performance gates through native/interpreter execution on x86-64, Apple Silicon macOS, and Android arm64-v8a",
      state: "missing",
    },
    {
      sourceId: "S024",
      label:
        "Offline translator, generated corpus/dispatcher, generation-only seeds, and static-only tests are absent",
      state: "verified",
    },
    {
      sourceId: "S025",
      label: "Asset-free source-policy CI runs from a full-history checkout",
      state: "verified",
    },
    {
      sourceId: "S026",
      label: "Windows CI produces an asset-free package from the native/interpreter product",
      state: "verified",
    },
    {
      sourceId: "S027",
      label: "macOS CI produces an Apple Silicon `.app` from the native/interpreter product",
      state: "verified",
    },
    {
      sourceId: "S028",
      label: "Linux CI produces an asset-free x86-64 AppImage",
      state: "verified",
    },
    {
      sourceId: "S029",
      label: "Android CI produces a signed arm64-v8a release APK",
      state: "partial",
    },
    {
      sourceId: "S030",
      label: "WASM builds and deploys the same product boundary to GitHub Pages",
      state: "verified",
    },
    {
      sourceId: "S031",
      label: "Desktop and browser first-run setup browse for and validate the three player disks",
      state: "partial",
    },
    {
      sourceId: "S032",
      label: "A version tag publishes one GitHub Release with all four native packages",
      state: "verified",
    },
    {
      sourceId: "S033",
      label:
        "One version identifies the whole product: the build banner, the pause panel, the Android package, and the published tag all name the same release",
      state: "verified",
    },
    {
      sourceId: "S034",
      label:
        "The product asks the release service once per launch whether a newer version exists and reports the answer without ever claiming a check that did not run succeeded",
      state: "partial",
    },
    {
      sourceId: "S035",
      label: "Every shipped platform presents an authored app icon instead of a placeholder",
      state: "verified",
    },
  ],
  sunbright: [
    {
      sourceId: "S001",
      label:
        "Exact `GMSE01` boots under `gcnport`/Dolphin JIT and reaches the `J3DShape::draw` runtime hook at `0x802e0390`",
      state: "verified",
    },
    {
      sourceId: "S002",
      label:
        "`gcnport` supplies a title-neutral Dolphin dynarec executor with image identity, bounded exits, invalidation, and diagnostics",
      state: "partial",
    },
    {
      sourceId: "S003",
      label:
        "Sunbright native overrides and original calls use robust image-scoped runtime dispatch",
      state: "partial",
    },
    {
      sourceId: "S004",
      label:
        "The PC-native semantic renderer covers the complete visible J3D/J2D/particle/effect stream",
      state: "partial",
    },
    {
      sourceId: "S005",
      label:
        "Native decomp adapters and recovered source provide independent semantic and behavior evidence",
      state: "partial",
    },
    {
      sourceId: "S006",
      label:
        "Smooth presentation covers every eligible moving source and keeps native-rate modes separate",
      state: "partial",
    },
    {
      sourceId: "S007",
      label: "Reached decomp behavior is upstream-converged, named, and implemented from evidence",
      state: "partial",
    },
    {
      sourceId: "S008",
      label: "The native/dynarec product passes representative interactive gameplay conformance",
      state: "missing",
    },
    {
      sourceId: "S009",
      label:
        "Offline generator, emitted corpus, static dispatcher/runtime glue, tests, and launch paths are absent",
      state: "verified",
    },
    {
      sourceId: "S010",
      label:
        "Independent Dolphin/decomp/binary oracle evidence can locate first divergence and prove controls",
      state: "verified",
    },
    {
      sourceId: "S011",
      label: "Native audio is complete and integrated with the native/dynarec gameplay product",
      state: "partial",
    },
    {
      sourceId: "S012",
      label:
        "Application lifecycle, typed configuration, Lucent logging, and structure boundaries are mechanically enforced",
      state: "partial",
    },
    {
      sourceId: "S013",
      label:
        "Zero-argument launcher provisions and runs only the native/dynarec product from a user-supplied image",
      state: "blocked",
    },
    {
      sourceId: "S017",
      label:
        "JIT gameplay is qualified independently on x86_64, Apple Silicon macOS AArch64, and Android arm64-v8a",
      state: "missing",
    },
    {
      sourceId: "S018",
      label:
        "Asset-free automation verifies the redistributable native renderer and tooling on supported hosts",
      state: "partial",
    },
    {
      sourceId: "S014",
      label: "Desktop packages provide no-terminal first-run setup and contain no game content",
      state: "missing",
    },
    {
      sourceId: "S015",
      label:
        "Widescreen renders additional world coverage through projection/viewport/scissor ownership",
      state: "partial",
    },
    {
      sourceId: "S016",
      label: "Native input, controls, saves, and settings work through one typed product policy",
      state: "partial",
    },
  ],
  zelda3d: [
    {
      sourceId: "S001",
      label:
        "One launcher provisions, validates, builds, and chooses between the OoT and MM game cores",
      state: "verified",
    },
    {
      sourceId: "S002",
      label:
        "3DS containers, models, animations, scenes, collision, cameras, lighting, and face data are available to both engines",
      state: "partial",
    },
    {
      sourceId: "S003",
      label:
        "The PC renderer reproduces the reached PICA200 material, texture, lighting, fog, and transparency semantics",
      state: "partial",
    },
    {
      sourceId: "S004",
      label:
        "OoT3D actor animation, facial, camera, and game-specific behavior replaces N64 behavior where grounded",
      state: "partial",
    },
    {
      sourceId: "S005",
      label:
        "MM3D actor animation, presentation, and game-specific behavior replaces N64 behavior where grounded",
      state: "partial",
    },
    {
      sourceId: "S006",
      label:
        "An embedded Azahar oracle and parity tooling can compare the port with independent 3DS execution",
      state: "partial",
    },
    {
      sourceId: "S007",
      label:
        "The AppImage accepts four direct ROMs or bounded ZIPs and persists validated choices without shipping game content",
      state: "partial",
    },
    {
      sourceId: "S008",
      label:
        "Linux CI builds the complete app and both cores and executes asset-free native contracts",
      state: "partial",
    },
    {
      sourceId: "S009",
      label: "macOS arm64 CI exercises portable policy seams; complete app delivery remains open",
      state: "partial",
    },
    {
      sourceId: "S010",
      label:
        "Windows x86_64 CI exercises portable policy seams; complete app delivery remains open",
      state: "partial",
    },
    {
      sourceId: "S011",
      label: "Android has a native package target and an asset-free CI gate",
      state: "missing",
    },
  ],
  xmen2: [
    {
      sourceId: "S001",
      label: "Fresh-clone provisioning and the default native launcher",
      state: "partial",
    },
    {
      sourceId: "S002",
      label: "Native-overrides + x86port-JIT gameplay execution",
      state: "partial",
    },
    {
      sourceId: "S003",
      label: "Faithful rendering of the reached game path",
      state: "partial",
    },
    {
      sourceId: "S004",
      label: "Native Alchemy 2D/UI rendering above the D3D8 seam",
      state: "partial",
    },
    {
      sourceId: "S005",
      label: "Native audio mixing and SFD movie playback",
      state: "verified",
    },
    {
      sourceId: "S006",
      label: "SDL3 keyboard/controller/mouse input, assignment, and hotswap",
      state: "partial",
    },
    {
      sourceId: "S007",
      label: "Xbox-derived controller defaults and source-sensitive prompts",
      state: "partial",
    },
    {
      sourceId: "S008",
      label: "Port-owned RmlUi settings and input-binding surface",
      state: "partial",
    },
    {
      sourceId: "S009",
      label: "Direct development boot into an initialized game",
      state: "partial",
    },
    {
      sourceId: "S010",
      label: "Measured frame and level-load performance",
      state: "partial",
    },
    {
      sourceId: "S011",
      label: "Wine oracle and evidence-backed differential RE workflow",
      state: "partial",
    },
    {
      sourceId: "S012",
      label: "A/B-toggleable native overrides and incremental engine replacement",
      state: "partial",
    },
    {
      sourceId: "S014",
      label: "Apple Silicon macOS native host support",
      state: "partial",
    },
    {
      sourceId: "S015",
      label: "Transactional autosave and direct retail Continue restore",
      state: "verified",
    },
    {
      sourceId: "S016",
      label: "Live control, capture, input, and runtime diagnostic channel",
      state: "verified",
    },
    {
      sourceId: "S017",
      label: "Linux AppImage packaging and no-terminal install setup",
      state: "partial",
    },
    {
      sourceId: "S018",
      label: "Android APK shell and measured mobile performance",
      state: "partial",
    },
    {
      sourceId: "S020",
      label: "Platform-neutral touch play on any touchscreen",
      state: "partial",
    },
    {
      sourceId: "S021",
      label: "Web (WASM + PWA) product with browser-side install",
      state: "partial",
    },
    {
      sourceId: "S022",
      label: "Native Windows host package and CI release",
      state: "missing",
    },
    {
      sourceId: "S023",
      label: "Seamless LAN multiplayer without GameSpy's servers",
      state: "partial",
    },
    {
      sourceId: "S019",
      label: "Proven shared Alchemy gameplay boundary and deferred MUA adoption",
      state: "partial",
    },
  ],
  "lf2-port": [
    {
      sourceId: "S001",
      label: "The intended product boots, navigates menus, and plays VS and Stage Mode with audio",
      state: "partial",
    },
    {
      sourceId: "S002",
      label: "High-resolution rendering preserves the game's pixel-art presentation",
      state: "verified",
    },
    {
      sourceId: "S003",
      label: "Keyboard and controller actions are remappable and persist across runs",
      state: "partial",
    },
    {
      sourceId: "S004",
      label: "The Linux AppImage provides no-terminal first-run game-file setup",
      state: "partial",
    },
    {
      sourceId: "S005",
      label: "Native overrides plus `x86port` JIT execute the authenticated LF2 image at runtime",
      state: "partial",
    },
    {
      sourceId: "S006",
      label:
        "Widescreen and ultrawide expand the visible stage instead of stretching the 4:3 picture",
      state: "verified",
    },
    {
      sourceId: "S007",
      label: "Native character lighting and cast shadows are configurable in the port menu",
      state: "verified",
    },
    {
      sourceId: "S008",
      label: "Two physical controllers join as two local players without manual slot setup",
      state: "partial",
    },
    {
      sourceId: "S009",
      label: "Controllers connect, disconnect, and reconnect without restarting the game",
      state: "partial",
    },
    {
      sourceId: "S010",
      label: "Borderless, windowed, fullscreen, and Alt+Enter display switching work",
      state: "verified",
    },
    {
      sourceId: "S011",
      label: "Menus and character selection use modern anti-aliased host text",
      state: "verified",
    },
    {
      sourceId: "S012",
      label: "The macOS native/JIT build and Metal renderer are release-qualified",
      state: "partial",
    },
    {
      sourceId: "S013",
      label:
        "The Android ARM64 native/JIT build provides touch controls and private installer/folder/ZIP setup",
      state: "partial",
    },
    {
      sourceId: "S014",
      label: "Custom LAN multiplayer supports remote player inputs",
      state: "missing",
    },
    {
      sourceId: "S015",
      label:
        "Representative gameplay conforms through the native/JIT product on each released host",
      state: "missing",
    },
    {
      sourceId: "S016",
      label:
        "Gameplay defaults to JIT, exposes no explicit interpreter mode, and accounts for bounded fallback by reason and coverage",
      state: "partial",
    },
    {
      sourceId: "S017",
      label: "Retired title-specific execution interfaces and toolchains remain absent",
      state: "verified",
    },
    {
      sourceId: "S018",
      label: "`shared/x86port` supplies the x86-64 product JIT and bounded fallback contract",
      state: "partial",
    },
    {
      sourceId: "S019",
      label:
        "`shared/x86port` supplies a qualified ARM64 product JIT backend for macOS and Android",
      state: "partial",
    },
    {
      sourceId: "S020",
      label: "Asset-free Linux x86-64 native/JIT product CI runs from exact full-history inputs",
      state: "partial",
    },
    {
      sourceId: "S021",
      label: "Browser WebAssembly runs the same native/JIT game with persistent imported files",
      state: "partial",
    },
    {
      sourceId: "S022",
      label:
        "Internet multiplayer discovers sessions through Firebase and carries gameplay peer-to-peer",
      state: "missing",
    },
    {
      sourceId: "S023",
      label: "Rollback netplay restores and resimulates exact game state",
      state: "missing",
    },
  ],
  "tomba2-engine": [
    {
      sourceId: "S001",
      label: "Tomba! 2 reaches representative gameplay as a native/Lightrec product",
      state: "blocked",
    },
    {
      sourceId: "S002",
      label: "Tomba! 2 behavior is independently compared against the original",
      state: "partial",
    },
    {
      sourceId: "S003",
      label: "Tomba! 2 game behavior is owned by readable native subsystems",
      state: "partial",
    },
    {
      sourceId: "S004",
      label: "Tomba! 2 picture is produced completely from game-owned scene state",
      state: "partial",
    },
    {
      sourceId: "S005",
      label: "Tomba! 2 true widescreen covers world visibility and 2D layout",
      state: "partial",
    },
    {
      sourceId: "S006",
      label: "Tomba! 2 interpolation covers moving camera, objects, and effects",
      state: "partial",
    },
    {
      sourceId: "S007",
      label: "Tomba! 2 accepts native player input through representative gameplay",
      state: "partial",
    },
    {
      sourceId: "S008",
      label: "Tomba! 1 selected executable and disc provenance are established",
      state: "verified",
    },
    {
      sourceId: "S009",
      label: "Tomba! 1 identity, isolation, and independent startup evidence exist",
      state: "verified",
    },
    {
      sourceId: "S010",
      label: "Tomba! 1 reaches representative gameplay as a native/Lightrec product",
      state: "missing",
    },
    {
      sourceId: "S011",
      label: "Tomba! 1 true widescreen works in the actual product",
      state: "missing",
    },
    {
      sourceId: "S012",
      label: "Tomba! 1 and Tomba! 2 game-engine implementations are isolated",
      state: "verified",
    },
    {
      sourceId: "S013",
      label: "Tomba! 1 exposes widescreen only and no unrelated enhancement modes",
      state: "verified",
    },
    {
      sourceId: "S014",
      label: "Tomba! 2 sound effects and music work throughout the game",
      state: "partial",
    },
    {
      sourceId: "S015",
      label: "Tomba! 2 saves, reloads, and survives a full restart",
      state: "partial",
    },
    {
      sourceId: "S016",
      label: "Tomba! 2 movies play correctly",
      state: "partial",
    },
    {
      sourceId: "S017",
      label: "Tomba! 2 area and scene transitions work throughout the game",
      state: "partial",
    },
    {
      sourceId: "S018",
      label: "Both titles have removed their offline guest-source product paths",
      state: "verified",
    },
    {
      sourceId: "S019",
      label: "Linux x86-64 asset-free native/Lightrec CI builds and tests the repository",
      state: "verified",
    },
    {
      sourceId: "S020",
      label: "Windows x86-64 native/Lightrec CI builds and tests the repository",
      state: "missing",
    },
    {
      sourceId: "S021",
      label: "macOS x86-64 and arm64 native/Lightrec CI builds and tests the repository",
      state: "missing",
    },
    {
      sourceId: "S022",
      label: "Android arm64-v8a native/Lightrec CI assembles and tests the repository",
      state: "missing",
    },
  ],
  "crash-bash": [
    {
      sourceId: "S001",
      label:
        "The selected USA disc, executable, and measured `CRASHBSH.DAT` modules are reproducibly authenticated and provisioned",
      state: "verified",
    },
    {
      sourceId: "S002",
      label:
        "The retail boot and loaded-image sequence have a recorded first-frame and menu frontier to re-establish through the dynarec",
      state: "partial",
    },
    {
      sourceId: "S003",
      label:
        "The gameplay product executes every non-native guest path through psxport's pinned Lightrec dynarec with bounded, reason-accounted fallback",
      state: "partial",
    },
    {
      sourceId: "S004",
      label:
        "Crash Bash graphics are produced natively from decoded game state and look correct across representative content",
      state: "partial",
    },
    {
      sourceId: "S005",
      label: "The native camera supports wider aspect ratios without changing vertical framing",
      state: "partial",
    },
    {
      sourceId: "S006",
      label: "Native camera and world transforms render between simulation ticks",
      state: "partial",
    },
    {
      sourceId: "S007",
      label:
        "Deterministic diagnostics compare reached hybrid-product boundaries with independent retail behavior and prove both answers",
      state: "partial",
    },
    {
      sourceId: "S008",
      label: "The retail game modes are reachable and playable end to end on the hybrid product",
      state: "partial",
    },
    {
      sourceId: "S009",
      label: "The Crashball gameplay scenario reaches a live match and accepts player control",
      state: "verified",
    },
    {
      sourceId: "S010",
      label: "Battle Mode Crate Crush reaches a live match and accepts player control",
      state: "verified",
    },
    {
      sourceId: "S011",
      label: "Tournament Mode reaches its first live Crate Crush match and accepts player control",
      state: "verified",
    },
    {
      sourceId: "S012",
      label: "Polar Push reaches a visually correct, controllable live match",
      state: "verified",
    },
    {
      sourceId: "S013",
      label: "The remaining retail modes are reachable and playable",
      state: "missing",
    },
    {
      sourceId: "S014",
      label: "Retail music and sound effects play at the correct rate without premature truncation",
      state: "partial",
    },
    {
      sourceId: "S015",
      label:
        "All 27 native overrides install by runtime image identity and all 15 original-body calls execute through the dynarec",
      state: "partial",
    },
    {
      sourceId: "S016",
      label: "Representative interactive gameplay passes on the native/dynarec product",
      state: "missing",
    },
    {
      sourceId: "S017",
      label:
        "Every static product path is deleted before dynarec implementation and mechanically excluded",
      state: "verified",
    },
    {
      sourceId: "S018",
      label:
        "Hosted CI truthfully covers applicable Linux, Windows, macOS, and Android product boundaries",
      state: "partial",
    },
  ],
  gears1: [
    {
      sourceId: "S001",
      label: "Exact Gears 1 executable identity and normalized image validation",
      state: "verified",
    },
    {
      sourceId: "S002",
      label: "Bounded user-image/archive provisioning without derived guest source",
      state: "partial",
    },
    {
      sourceId: "S003",
      label: "Executor-independent native renderer and RHI contracts",
      state: "partial",
    },
    {
      sourceId: "S004",
      label: "Native Gears 1 audio-mix operation",
      state: "verified",
    },
    {
      sourceId: "S005",
      label: "Native notified operation-kind-3 GPU ticket wait",
      state: "partial",
    },
    {
      sourceId: "S006",
      label: "Xenia-backed `x360port` execution boundary",
      state: "partial",
    },
    {
      sourceId: "S007",
      label: "Gears 1 leaf/import/override discriminator",
      state: "partial",
    },
    {
      sourceId: "S008",
      label: "Bounded runtime interpreter fallback",
      state: "partial",
    },
    {
      sourceId: "S009",
      label: "Representative interactive Gears 1 gameplay",
      state: "partial",
    },
    {
      sourceId: "S010",
      label: "Apple Silicon macOS A64 execution",
      state: "partial",
    },
    {
      sourceId: "S011",
      label: "Android arm64-v8a A64 execution",
      state: "missing",
    },
    {
      sourceId: "S012",
      label: "Complete native RHI frontend",
      state: "missing",
    },
    {
      sourceId: "S013",
      label: "Native 8.33 ms / 120 fps renderer budget",
      state: "partial",
    },
    {
      sourceId: "S014",
      label: "Gears 2, Gears 3, and Judgment exact-revision conformance",
      state: "missing",
    },
    {
      sourceId: "S015",
      label: "Generated guest-source product and translator-only surfaces absent",
      state: "verified",
    },
    {
      sourceId: "S016",
      label: "Independently authored shared UE3/Xbox contract",
      state: "verified",
    },
    {
      sourceId: "S017",
      label: "Asset-free native/JIT boundary CI",
      state: "partial",
    },
    {
      sourceId: "S018",
      label: "PC keyboard and mouse controls beside host gamepads",
      state: "partial",
    },
    {
      sourceId: "S019",
      label: "Campaign checkpoints save and resume in the player's user-data directory",
      state: "verified",
    },
    {
      sourceId: "S020",
      label: "Native engine reads Gears 1's cooked packages without the guest",
      state: "verified",
    },
    {
      sourceId: "S021",
      label: "Native engine reads objects' serialized properties",
      state: "verified",
    },
    {
      sourceId: "S022",
      label: "Native engine decodes textures and static meshes and renders a level",
      state: "partial",
    },
  ],
  psxport: [
    {
      sourceId: "S012",
      label: "Per-`Core` dynarec-default Lightrec backend",
      state: "partial",
    },
    {
      sourceId: "S013",
      label: "Explicit architectural state and bounded exits",
      state: "partial",
    },
    {
      sourceId: "S014",
      label: "Image/generation-scoped native and original calls",
      state: "partial",
    },
    {
      sourceId: "S015",
      label: "Central executable-code invalidation",
      state: "partial",
    },
    {
      sourceId: "S016",
      label: "Product path excludes offline guest generation and unbounded interpreter modes",
      state: "verified",
    },
    {
      sourceId: "S017",
      label: "Reusable native PSX platform services",
      state: "partial",
    },
    {
      sourceId: "S018",
      label: "Independent test oracle",
      state: "partial",
    },
    {
      sourceId: "S019",
      label: "Narrow multi-title framework seam",
      state: "partial",
    },
    {
      sourceId: "S020",
      label: "Native rendering and title-owned enhancements",
      state: "partial",
    },
    {
      sourceId: "S021",
      label: "Portable desktop and Android delivery",
      state: "missing",
    },
    {
      sourceId: "S022",
      label: "Mechanical structure/config/logging/tooling policy",
      state: "partial",
    },
  ],
  lucent: [
    {
      sourceId: "S001",
      label: "One channel-based logger provides configurable portable process diagnostics",
      state: "verified",
    },
    {
      sourceId: "S002",
      label: "Applications resolve and create private OS-native user-data directories",
      state: "verified",
    },
    {
      sourceId: "S003",
      label:
        "A bounded local HTTP server owns request parsing, framing, concurrency, scope, and lifecycle",
      state: "verified",
    },
    {
      sourceId: "S004",
      label:
        "Streaming content identity validates player-owned files without loading them completely into memory",
      state: "verified",
    },
    {
      sourceId: "S005",
      label: "Platform-neutral multi-touch routing owns contact capture, zones, and cancellation",
      state: "verified",
    },
    {
      sourceId: "S007",
      label: "HTTP responses stream bounded files without loading complete media into memory",
      state: "verified",
    },
    {
      sourceId: "S008",
      label: "Typed configuration reads named application settings from portable process inputs",
      state: "verified",
    },
    {
      sourceId: "S009",
      label: "Bounded ZIP discovery and extraction safely imports exactly one selected payload",
      state: "verified",
    },
    {
      sourceId: "S010",
      label:
        "Native CMake and CTest verification runs on supported desktop hosts without game assets",
      state: "partial",
    },
    {
      sourceId: "S011",
      label: "Linux applications select one local file asynchronously through a native GTK chooser",
      state: "partial",
    },
    {
      sourceId: "S012",
      label: "Linux applications read regular files asynchronously within a strict byte budget",
      state: "verified",
    },
    {
      sourceId: "S013",
      label:
        "Linux applications stage immutable binary backing files asynchronously with bounded lifetime storage",
      state: "verified",
    },
  ],
  alchemy: [
    {
      sourceId: "S001",
      label: "IGB containers and the measured Xbox 360 and PS2 corpora can be opened and inspected",
      state: "verified",
    },
    {
      sourceId: "S002",
      label: "Mesh, texture, raster, and animation payloads decode into native semantic data",
      state: "partial",
    },
    {
      sourceId: "S003",
      label:
        "XMLB, FB/WAD, ARK class, font, and conversation tooling exposes reusable engine formats",
      state: "partial",
    },
    {
      sourceId: "S004",
      label:
        "Platform-neutral controller snapshots and an SDL3 backend support stable native devices",
      state: "partial",
    },
    {
      sourceId: "S005",
      label:
        "Existing standalone viewers and dump tools inspect measured assets without depending on a game port",
      state: "verified",
    },
    {
      sourceId: "S006",
      label: "IGB meshes decode into native vertex, index, material, and skinning data",
      state: "partial",
    },
    {
      sourceId: "S007",
      label: "Xbox 360 and PS2 texture/raster payloads decode into native images",
      state: "partial",
    },
    {
      sourceId: "S008",
      label: "Enbaya-compressed animation payloads decode into native animation data",
      state: "partial",
    },
    {
      sourceId: "S009",
      label: "XMLB assets can be decoded, edited, and round-tripped by shared tooling",
      state: "partial",
    },
    {
      sourceId: "S010",
      label:
        "FB/WAD, ARK class/vtable, font, and conversation formats have reusable inspection tools",
      state: "partial",
    },
    {
      sourceId: "S011",
      label: "X-Men 2 gameplay links and executes a conformed shared Alchemy contract",
      state: "missing",
    },
    {
      sourceId: "S012",
      label: "MUA gameplay links and executes proven shared Alchemy contracts",
      state: "missing",
    },
    {
      sourceId: "S013",
      label:
        "Shipping library configuration, diagnostics, language, and dependency boundaries are mechanically enforced",
      state: "verified",
    },
    {
      sourceId: "S014",
      label: "Each consumer resolves one immutable Alchemy revision for tools and runtime targets",
      state: "partial",
    },
  ],
  "port-assets": [
    {
      sourceId: "S001",
      label: "Generic keyboard and gamepad device indicators are available as original SVGs",
      state: "verified",
    },
    {
      sourceId: "S002",
      label:
        "A complete Xbox 360-style controller prompt family covers buttons, triggers, sticks, and directions",
      state: "verified",
    },
    {
      sourceId: "S003",
      label: "Label-neutral keyboard keycaps can display the consumer's actual binding",
      state: "verified",
    },
    {
      sourceId: "S004",
      label: "Authored touch-direction controls provide distinct up, down, left, and right prompts",
      state: "verified",
    },
    {
      sourceId: "S005",
      label:
        "Manifests and authoring checks prevent missing, stale, or indistinguishable glyphs, with target-background review required for legibility",
      state: "verified",
    },
    {
      sourceId: "S006",
      label: "Asset authoring and target-size raster checks run in hosted verification",
      state: "partial",
    },
  ],
  pinest: [
    {
      sourceId: "S1",
      label: "PiNest extension is ported and loads under pi",
      state: "verified",
    },
    {
      sourceId: "S2",
      label: "Session registry is private, owner-bound, and persisted to disk",
      state: "verified",
    },
    {
      sourceId: "S3",
      label: "Sessions survive a real host crash/restart and resume with full history",
      state: "partial",
    },
    {
      sourceId: "S4",
      label: "Explicit live harness reload adopts running sessions safely",
      state: "verified",
    },
    {
      sourceId: "S5b",
      label: "Hosted discovery and browser authentication provide zero-config distribution",
      state: "partial",
    },
    {
      sourceId: "S5",
      label: "GLM-5.3-Flash defaults to a one-million-token context with configured compaction",
      state: "verified",
    },
    {
      sourceId: "S6",
      label: "Flutter clients provide durable remote session control and release delivery",
      state: "partial",
    },
    {
      sourceId: "S7",
      label:
        "One owner is isolated through hardened authentication, protocol, discovery, and release boundaries",
      state: "partial",
    },
    {
      sourceId: "S8",
      label:
        "Remote clients create, list, resume, rename, and delete sessions across project directories",
      state: "partial",
    },
    {
      sourceId: "S9",
      label:
        "Remote clients stream conversations, steer or queue input, paste images, inspect tools, and stop runs",
      state: "partial",
    },
    {
      sourceId: "S10",
      label: "Clients show model/context usage and expose automatic and manual compaction controls",
      state: "partial",
    },
    {
      sourceId: "S11",
      label:
        "The authenticated web client connects to the owner's advertised host over the internet",
      state: "partial",
    },
    {
      sourceId: "S12",
      label: "An installable, attested Android APK is published for the mobile client",
      state: "verified",
    },
    {
      sourceId: "S13",
      label: "The mobile client is distributed through Google Play",
      state: "missing",
    },
    {
      sourceId: "S14",
      label: "History transport is bounded and images load on demand",
      state: "verified",
    },
    {
      sourceId: "S15",
      label: "Remote access works with no third party in the data path (direct WebRTC transport)",
      state: "partial",
    },
    {
      sourceId: "S16",
      label: "A send is reported undelivered only when the refusal names THAT send",
      state: "verified",
    },
    {
      sourceId: "S17",
      label: "A compaction with nothing to compact is a no-op, and is not re-attempted",
      state: "verified",
    },
    {
      sourceId: "S18",
      label: "Concurrent notices are stacked, deduplicated, and bounded",
      state: "verified",
    },
    {
      sourceId: "S19",
      label: "A session states it has no context budget, so agents do not invent one and stop",
      state: "partial",
    },
    {
      sourceId: "S20",
      label: "The objective belongs to the session it was set for, and shows only on that tab",
      state: "verified",
    },
    {
      sourceId: "S21",
      label: "Instructions the harness injects are never shown as the user's own words",
      state: "verified",
    },
    {
      sourceId: "S22",
      label: "The host terminal lists its sessions, opens any of them, and prompts it from there",
      state: "partial",
    },
  ],
  "node-gtk-vte": [
    {
      sourceId: "S001",
      label:
        "Bun loads GTK 3, VTE 2.91, and GObject directly and can construct a native terminal window",
      state: "partial",
    },
    {
      sourceId: "S002",
      label: "Applications can feed terminal output and receive translated user input bytes",
      state: "partial",
    },
    {
      sourceId: "S003",
      label:
        "GTK window, container, notebook, label, button, menu, image, overlay, alignment, and CSS bindings support application composition",
      state: "partial",
    },
    {
      sourceId: "S004",
      label:
        "Helpers retain native strings and callbacks and release connected handlers explicitly",
      state: "partial",
    },
    {
      sourceId: "S005",
      label:
        "Automated controls verify the FFI surface, lifecycle helpers, and failure behavior on a real Linux runtime",
      state: "missing",
    },
  ],
  "re-harness": [
    {
      sourceId: "S001",
      label: "Project-agnostic skills are packaged under the global scope",
      state: "verified",
    },
    {
      sourceId: "S002",
      label: "Port architecture guidance is usable without the dynarec stack",
      state: "verified",
    },
    {
      sourceId: "S003",
      label:
        "Reverse-engineering skills are grouped independently of runtime-execution methodology",
      state: "verified",
    },
    {
      sourceId: "S004",
      label: "Dynamic guest-execution skills replace the removed generated-source methodology",
      state: "verified",
    },
    {
      sourceId: "S005",
      label: "Reusable CLIs have canonical implementations and stable compatibility entry points",
      state: "verified",
    },
    {
      sourceId: "S006",
      label:
        "Codex, Claude, and generic agent homes converge instructions, skills, and tools through safe relative links",
      state: "verified",
    },
    {
      sourceId: "S007",
      label: "The shared tools and installer have positive and negative verification controls",
      state: "verified",
    },
    {
      sourceId: "S008",
      label:
        "Global project guidance requires every maintained project and catalogue to expose a complete stateful intended-feature inventory",
      state: "verified",
    },
    {
      sourceId: "S009",
      label: "Hosted CI exercises the portable repository on every applicable platform",
      state: "verified",
    },
  ],
  "wails-dbman": [
    {
      sourceId: "S001",
      label: "Users can add, edit, remove, persist, and test database connections",
      state: "partial",
    },
    {
      sourceId: "S002",
      label: "The explorer discovers SQL Server databases, tables, views, and stored procedures",
      state: "partial",
    },
    {
      sourceId: "S003",
      label:
        "Query tabs provide a Monaco SQL editor with schema-aware completion and keyboard execution",
      state: "partial",
    },
    {
      sourceId: "S004",
      label: "Table tabs expose data with paging, sorting, filtering, and resizable columns",
      state: "partial",
    },
    {
      sourceId: "S005",
      label: "PostgreSQL and MySQL provide feature-equivalent discovery and query behavior",
      state: "missing",
    },
    {
      sourceId: "S006",
      label: "Open tabs persist and restore as one desktop workspace",
      state: "partial",
    },
    {
      sourceId: "S007",
      label: "Query execution displays multiple result sets, row counts, errors, and timing",
      state: "partial",
    },
    {
      sourceId: "S008",
      label: "View and stored-procedure tabs expose schemas and definitions",
      state: "partial",
    },
    {
      sourceId: "S009",
      label: "The desktop supports persistent light and dark themes",
      state: "partial",
    },
    {
      sourceId: "S010",
      label: "The database explorer can be resized without losing its layout",
      state: "partial",
    },
    {
      sourceId: "S011",
      label: "Global object search is keyboard-navigable across the connected server",
      state: "partial",
    },
    {
      sourceId: "S012",
      label: "Desktop releases provide verified Windows, macOS, and Linux packages",
      state: "partial",
    },
  ],
  "wails-cast": [
    {
      sourceId: "S001",
      label:
        "The desktop discovers Chromecast devices and controls play, pause, stop, seek, volume, and mute",
      state: "partial",
    },
    {
      sourceId: "S002",
      label:
        "Local files, remote URLs, HLS streams, track selection, transcoding, and cache reuse form one playback pipeline",
      state: "partial",
    },
    {
      sourceId: "S003",
      label:
        "Background downloads, extraction, translation, progress, cancellation, and resume preserve valid state",
      state: "partial",
    },
    {
      sourceId: "S004",
      label:
        "Embedded, nearby, external, translated, and burned-in subtitle workflows are available per episode",
      state: "partial",
    },
    {
      sourceId: "S005",
      label:
        "Library scanning, identification, organization, seasons, episodes, and torrent submission support media management",
      state: "partial",
    },
    {
      sourceId: "S006",
      label:
        "A token-protected advertised Remote API exposes library, playback, subtitle, translation, and settings operations",
      state: "partial",
    },
    {
      sourceId: "S007",
      label: "Chromecast devices are discovered automatically over mDNS",
      state: "partial",
    },
    {
      sourceId: "S008",
      label: "Play, pause, stop, seek, volume, and mute control the selected Chromecast",
      state: "partial",
    },
    {
      sourceId: "S009",
      label: "Local files can be probed, prepared, and cast",
      state: "partial",
    },
    {
      sourceId: "S010",
      label: "Remote URLs and HLS streams can be extracted, prepared, and cast",
      state: "partial",
    },
    {
      sourceId: "S011",
      label: "Unsupported media is transcoded and reusable results are cached",
      state: "partial",
    },
    {
      sourceId: "S012",
      label:
        "Downloads and extraction expose progress, cancellation, and resume without corrupting state",
      state: "partial",
    },
    {
      sourceId: "S013",
      label: "Embedded, nearby, and external subtitle tracks can be selected per episode",
      state: "partial",
    },
    {
      sourceId: "S014",
      label: "Subtitles can be translated, synchronized, exported, or burned into video",
      state: "partial",
    },
    {
      sourceId: "S015",
      label: "Shows are identified and organized into seasons and episodes in a local library",
      state: "partial",
    },
    {
      sourceId: "S016",
      label: "Torrent submissions enter the same managed media workflow",
      state: "partial",
    },
    {
      sourceId: "S017",
      label:
        "Remote API access is authenticated by token and advertised only through the configured scope",
      state: "partial",
    },
  ],
  "wails-cast-remote": [
    {
      sourceId: "S001",
      label:
        "The app discovers Wails Cast hosts over mDNS and supports manual authenticated connection",
      state: "partial",
    },
    {
      sourceId: "S002",
      label: "Users browse the remote library, refresh it, and submit arbitrary media URLs",
      state: "partial",
    },
    {
      sourceId: "S003",
      label: "Users select output device, video, audio, subtitle, and quality before playback",
      state: "partial",
    },
    {
      sourceId: "S004",
      label:
        "Now Playing provides live position, play, pause, stop, seek, volume, and mute controls",
      state: "partial",
    },
    {
      sourceId: "S005",
      label:
        "Subtitle translation, status, retranslation, and synced playback preferences work end to end",
      state: "partial",
    },
    {
      sourceId: "S006",
      label: "Android and iOS releases are qualified against the shipping desktop API",
      state: "missing",
    },
    {
      sourceId: "S007",
      label:
        "The client discovers desktop hosts over mDNS and also accepts manual host, port, and token entry",
      state: "partial",
    },
    {
      sourceId: "S008",
      label:
        "The remote library can be browsed and refreshed, and arbitrary media URLs can be submitted",
      state: "partial",
    },
    {
      sourceId: "S009",
      label:
        "Users choose the output device, video track, audio track, subtitle track, and quality before play",
      state: "partial",
    },
    {
      sourceId: "S010",
      label:
        "Now Playing shows live position and supports play, pause, stop, skip, scrubber seek, volume, and mute",
      state: "partial",
    },
    {
      sourceId: "S011",
      label:
        "Subtitle translation status, retranslation, selection, burn-in, and language preferences are available",
      state: "partial",
    },
    {
      sourceId: "S012",
      label: "The last authenticated desktop connection persists across app restarts",
      state: "partial",
    },
  ],
  "fedora-kde-steamdeck": [
    {
      sourceId: "S001",
      label:
        "Installation adds a Wayland session picker and Plasma shortcut for entering game mode",
      state: "partial",
    },
    {
      sourceId: "S002",
      label:
        "The selected session launches Steam Gamepad UI under fullscreen Gamescope and logs the run",
      state: "partial",
    },
    {
      sourceId: "S003",
      label: "Returning to desktop logs out through an available KDE or system session command",
      state: "partial",
    },
    {
      sourceId: "S004",
      label:
        "Installation and removal are documented, validated, and tested without leaving user files behind",
      state: "missing",
    },
  ],
  prismlauncher: [
    {
      sourceId: "S001",
      label: "The launcher manages and launches Minecraft instances",
      state: "verified",
    },
    {
      sourceId: "S002",
      label: "Instances can use the established archive import and export paths",
      state: "verified",
    },
    {
      sourceId: "S003",
      label: "Every running launcher automatically advertises its instance catalogue on the LAN",
      state: "verified",
    },
    {
      sourceId: "S004",
      label:
        "A recipient can discover and import an available instance from the New Instance window",
      state: "verified",
    },
    {
      sourceId: "S005",
      label:
        "LAN transfer uses a bounded capability and preserves the existing importer as archive authority",
      state: "verified",
    },
    {
      sourceId: "S006",
      label: "LAN import has focused positive and negative verification",
      state: "verified",
    },
    {
      sourceId: "S007",
      label: "Players can select, configure, and manage compatible Java runtimes",
      state: "verified",
    },
    {
      sourceId: "S008",
      label: "Players can authenticate or use the launcher-supported account workflows",
      state: "partial",
    },
    {
      sourceId: "S009",
      label: "Players can browse and install supported mod-platform content",
      state: "partial",
    },
    {
      sourceId: "S010",
      label: "Players can configure launcher presentation, logging, and updates",
      state: "partial",
    },
    {
      sourceId: "S011",
      label: "A selected instance can create a desktop shortcut using its instance name",
      state: "verified",
    },
    {
      sourceId: "S012",
      label: "The fork's installed Flatpak checks and installs stable fork releases automatically",
      state: "partial",
    },
    {
      sourceId: "S013",
      label: "Flatpak launcher data can be copied into a native installation",
      state: "partial",
    },
    {
      sourceId: "S014",
      label: "Fork releases provide a Linux AppImage, Flatpak, and native macOS arm64 app",
      state: "verified",
    },
    {
      sourceId: "S015",
      label:
        "A recipient can update an existing stopped local instance from a LAN instance while preserving local player data",
      state: "verified",
    },
  ],
  "minecraft-supermarket": [
    {
      sourceId: "S001",
      label: "A supermarket town is placed by Minecraft world generation",
      state: "verified",
    },
    {
      sourceId: "S002",
      label: "A player joining for the first time is placed at the generated shop door",
      state: "verified",
    },
    {
      sourceId: "S003",
      label: "New-world creation defaults to Survival on Easy difficulty",
      state: "verified",
    },
    {
      sourceId: "S004",
      label: "Hostile mobs are excluded from the city while equivalent threats remain outside it",
      state: "verified",
    },
    {
      sourceId: "S005",
      label:
        "The generated town contains an expanded city plus an internal sakura grove and surrounding sakura forest",
      state: "verified",
    },
    {
      sourceId: "S006",
      label: "The generated supermarket maintains a live customer population",
      state: "verified",
    },
    {
      sourceId: "S007",
      label:
        "Customers shop, approach and wait at the till, complete checkout after CHARGE, and leave",
      state: "verified",
    },
    {
      sourceId: "S008",
      label: "The supermarket exposes stocked retail inventory, including soda products",
      state: "verified",
    },
    {
      sourceId: "S009",
      label: "The generated supermarket has stocked ice-cream stands",
      state: "verified",
    },
    {
      sourceId: "S010",
      label: "The order computer starts a truck delivery that unloads goods and consumes the order",
      state: "verified",
    },
    {
      sourceId: "S011",
      label: "A portable, current Supermarket pack zip is available",
      state: "verified",
    },
    {
      sourceId: "S012",
      label: "Pack assembly is reproducible from declared portable inputs",
      state: "verified",
    },
    {
      sourceId: "S013",
      label: "Every verified milestone publishes a current pack through GitHub CI/CD",
      state: "verified",
    },
    {
      sourceId: "S014",
      label: "The modpack has a custom SVG visual identity used by its distribution",
      state: "verified",
    },
    {
      sourceId: "S015",
      label: "The normal verifier and project registries protect all goal-level behaviors",
      state: "verified",
    },
    {
      sourceId: "S016",
      label: "The complete Supermarket experience is operable with a standard game controller",
      state: "verified",
    },
    {
      sourceId: "S017",
      label: "The project has a version-controlled `main` branch and GitHub release substrate",
      state: "verified",
    },
    {
      sourceId: "S018",
      label: "A connected southern business district expands the generated city",
      state: "partial",
    },
    {
      sourceId: "S019",
      label: "The pack offers obtainable, usable cars and bicycles",
      state: "partial",
    },
    {
      sourceId: "S020",
      label: "City businesses have furnished, stocked interiors including real coffee",
      state: "partial",
    },
    {
      sourceId: "S021",
      label: "The supermarket has full-height stocked shelves and raised angled produce bins",
      state: "verified",
    },
  ],
  setsail: [
    {
      sourceId: "ST-BOOT",
      label: "Title boots to in-game control through our source-built runtime",
      state: "verified",
    },
    {
      sourceId: "ST-IDENT",
      label: "Title identity is validated from the player's file before it is accepted",
      state: "verified",
    },
    {
      sourceId: "ST-CAMERA",
      label: "Camera transform recovered from the guest's submitted render state",
      state: "verified",
    },
    {
      sourceId: "ST-ACTORS",
      label: "Actor transforms recovered with stable identity across ticks",
      state: "partial",
    },
    {
      sourceId: "ST-60",
      label: "Presents at 60 Hz with interpolated frames from blended transforms",
      state: "partial",
    },
    {
      sourceId: "ST-60-EVIDENCE",
      label: "Interpolation proven by counters with denominators and code-diffed captures",
      state: "partial",
    },
    {
      sourceId: "ST-PERF",
      label: "60 Hz sustained, frame-time percentiles published with the tested hardware",
      state: "verified",
    },
    {
      sourceId: "ST-SAVES",
      label: "Saves and settings in the OS user-data location, not the checkout",
      state: "verified",
    },
    {
      sourceId: "ST-SETUP",
      label: "No-terminal first-run setup with a native picker for the player's disc image",
      state: "verified",
    },
    {
      sourceId: "ST-APPIMAGE",
      label: "Asset-free Linux AppImage release",
      state: "verified",
    },
    {
      sourceId: "ST-RUNSH",
      label: "`./run.sh` provisions from a clean checkout and launches the title",
      state: "verified",
    },
    {
      sourceId: "ST-VERIFIER",
      label: "Canonical Python verifier with format, tidy, structure, and test gates",
      state: "verified",
    },
  ],
} as const satisfies Record<string, readonly ProjectFeature[]>;

export type ProjectSlug = keyof typeof featuresByProject;

export function featuresFor(slug: ProjectSlug): readonly ProjectFeature[] {
  return featuresByProject[slug];
}

export function comparisonBaselineFor(slug: ProjectSlug): string {
  return comparisonBaselinesByProject[slug];
}
