// Generated by tools/sync_project_features.py. Do not edit by hand.

export type ProjectFeatureState = "verified" | "partial" | "blocked" | "missing";

export interface ProjectFeature {
  sourceId: string;
  label: string;
  state: ProjectFeatureState;
}

const featuresByProject = {
  benefactor: [
    {
      sourceId: "S001",
      label:
        "The native desktop product boots and plays the retail game from player-supplied disks",
      state: "verified",
    },
    {
      sourceId: "S002",
      label:
        "Widescreen, speed, camera, difficulty, level selection, and persistent options work in the shipping game",
      state: "verified",
    },
    {
      sourceId: "S003",
      label:
        "Keyboard and hot-pluggable controller input support authentic, modern, and rebindable mappings",
      state: "verified",
    },
    {
      sourceId: "S004",
      label:
        "AppImage and Android releases provide no-terminal disk setup without packaging game assets",
      state: "verified",
    },
    {
      sourceId: "S005",
      label: "Recompiled M68K gameplay behavior is replaced by readable native engine subsystems",
      state: "partial",
    },
    {
      sourceId: "S006",
      label: "A differential PUAE harness compares the port with the original execution",
      state: "verified",
    },
  ],
  sunbright: [
    {
      sourceId: "S001",
      label: "The recomp runtime boots and renders the game through Aurora GX",
      state: "verified",
    },
    {
      sourceId: "S002",
      label:
        "The native decomp runtime boots and renders representative game flow through Aurora GX",
      state: "verified",
    },
    {
      sourceId: "S003",
      label: "The recomp has a project-owned SDL3-GPU GX compatibility/reference renderer",
      state: "partial",
    },
    {
      sourceId: "S004",
      label:
        "The recomp feeds ordered 2D/UI draws and rigid or multi-matrix solid-colour, textured, masked, diffuse, and specular J3D material families to the shared PC-native semantic renderer above GX",
      state: "partial",
    },
    {
      sourceId: "S005",
      label:
        "The native decomp feeds the same semantic 2D/UI and J3D material families to that renderer through native-layout adapters",
      state: "partial",
    },
    {
      sourceId: "S006",
      label:
        "Interpolated presentation covers every rendered target that should move between ticks",
      state: "partial",
    },
    {
      sourceId: "S007",
      label:
        "The native decomp is upstream-converged, semantically named, and complete for reached game behavior",
      state: "partial",
    },
  ],
  zelda3d: [
    {
      sourceId: "S001",
      label:
        "One launcher provisions, validates, builds, and chooses between the OoT and MM game cores",
      state: "verified",
    },
    {
      sourceId: "S002",
      label:
        "3DS containers, models, animations, scenes, collision, cameras, lighting, and face data are available to both engines",
      state: "partial",
    },
    {
      sourceId: "S003",
      label:
        "The PC renderer reproduces the reached PICA200 material, texture, lighting, fog, and transparency semantics",
      state: "partial",
    },
    {
      sourceId: "S004",
      label:
        "OoT3D actor animation, facial, camera, and game-specific behavior replaces N64 behavior where grounded",
      state: "partial",
    },
    {
      sourceId: "S005",
      label:
        "MM3D actor animation, presentation, and game-specific behavior replaces N64 behavior where grounded",
      state: "partial",
    },
    {
      sourceId: "S006",
      label:
        "An embedded Azahar oracle and parity tooling can compare the port with independent 3DS execution",
      state: "verified",
    },
    {
      sourceId: "S007",
      label:
        "The AppImage accepts four direct ROMs or bounded ZIPs and persists validated choices without shipping game content",
      state: "partial",
    },
  ],
  "xmen2-recomp": [
    {
      sourceId: "S001",
      label: "Fresh-clone provisioning and the default native launcher",
      state: "verified",
    },
    {
      sourceId: "S002",
      label: "Wine-free native execution of the recompiled PC game",
      state: "partial",
    },
    {
      sourceId: "S003",
      label: "Faithful rendering of the reached game path",
      state: "partial",
    },
    {
      sourceId: "S004",
      label: "Native Alchemy 2D/UI rendering above the D3D8 seam",
      state: "partial",
    },
    {
      sourceId: "S005",
      label: "Native audio mixing and SFD movie playback",
      state: "verified",
    },
    {
      sourceId: "S006",
      label: "SDL3 keyboard/controller/mouse input, assignment, and hotswap",
      state: "partial",
    },
    {
      sourceId: "S007",
      label: "Xbox-derived controller defaults and source-sensitive prompts",
      state: "partial",
    },
    {
      sourceId: "S008",
      label: "Port-owned RmlUi settings and input-binding surface",
      state: "partial",
    },
    {
      sourceId: "S009",
      label: "Direct development boot into an initialized game",
      state: "partial",
    },
    {
      sourceId: "S010",
      label: "Measured frame and level-load performance",
      state: "partial",
    },
    {
      sourceId: "S011",
      label: "Wine oracle and evidence-backed differential RE workflow",
      state: "partial",
    },
    {
      sourceId: "S012",
      label: "A/B-toggleable native overrides and incremental engine replacement",
      state: "partial",
    },
    {
      sourceId: "S013",
      label: "Secondary native recompilation of the Xbox build",
      state: "partial",
    },
    {
      sourceId: "S014",
      label: "Apple Silicon macOS native host support",
      state: "partial",
    },
    {
      sourceId: "S015",
      label: "Transactional autosave and direct retail Continue restore",
      state: "verified",
    },
    {
      sourceId: "S016",
      label: "Live control, capture, input, and runtime diagnostic channel",
      state: "verified",
    },
    {
      sourceId: "S017",
      label: "Linux AppImage packaging and no-terminal install setup",
      state: "partial",
    },
    {
      sourceId: "S018",
      label: "Android APK shell, touch controls, and measured mobile performance",
      state: "partial",
    },
  ],
  "lf2-port": [
    {
      sourceId: "S001",
      label: "The native port boots, navigates menus, and plays VS and Stage Mode with audio",
      state: "verified",
    },
    {
      sourceId: "S002",
      label: "The renderer provides high-resolution, widescreen, ultrawide, lighting, and shadows",
      state: "verified",
    },
    {
      sourceId: "S003",
      label:
        "Persistent keyboard and controller mappings support local multiplayer and hot-plug policy",
      state: "partial",
    },
    {
      sourceId: "S004",
      label: "Linux, macOS, and Android releases provide validated no-terminal game setup",
      state: "partial",
    },
    {
      sourceId: "S005",
      label:
        "The x86 game and Windows platform calls run through native static recompilation and SDL owners",
      state: "verified",
    },
  ],
  "tomba2-engine": [
    {
      sourceId: "S001",
      label: "Default Tomba! 2 product reaches a usable PC-native game",
      state: "partial",
    },
    {
      sourceId: "S002",
      label: "Tomba! 2 behavior is independently compared against the original",
      state: "partial",
    },
    {
      sourceId: "S003",
      label: "Tomba! 2 game behavior is owned by readable native subsystems",
      state: "partial",
    },
    {
      sourceId: "S004",
      label: "Tomba! 2 picture is produced completely from game-owned scene state",
      state: "partial",
    },
    {
      sourceId: "S005",
      label: "Tomba! 2 true widescreen covers world visibility and 2D layout",
      state: "partial",
    },
    {
      sourceId: "S006",
      label: "Tomba! 2 interpolation covers moving camera, objects, and effects",
      state: "partial",
    },
    {
      sourceId: "S007",
      label: "Tomba! 2 full-game input, audio, saves, movies, and transitions work",
      state: "partial",
    },
    {
      sourceId: "S008",
      label: "Tomba! 1 selected executable and disc provenance are established",
      state: "partial",
    },
    {
      sourceId: "S009",
      label: "Tomba! 1 evidence scaffold is integrated in the combined Clang build",
      state: "verified",
    },
    {
      sourceId: "S010",
      label: "Tomba! 1 actual product boots, renders, accepts input, and reaches gameplay",
      state: "missing",
    },
    {
      sourceId: "S011",
      label: "Tomba! 1 true widescreen works in the actual product",
      state: "missing",
    },
    {
      sourceId: "S012",
      label: "Tomba! 1 and Tomba! 2 game-engine implementations are isolated",
      state: "verified",
    },
    {
      sourceId: "S013",
      label: "Tomba! 1 exposes widescreen only and no unrelated enhancement modes",
      state: "verified",
    },
  ],
  "crash-bash": [
    {
      sourceId: "S001",
      label:
        "The selected USA disc, executable, and measured CRASHBSH.DAT code modules are reproducibly identified and derived",
      state: "verified",
    },
    {
      sourceId: "S002",
      label: "The retail boot reaches a guest-visible first frame with faithful drive timing",
      state: "partial",
    },
    {
      sourceId: "S003",
      label:
        "Resident code and every measured CRASHBSH.DAT module form a reproducible executable recompilation substrate",
      state: "verified",
    },
    {
      sourceId: "S004",
      label: "Crash Bash graphics are produced natively from decoded game state and look correct",
      state: "partial",
    },
    {
      sourceId: "S005",
      label: "The native camera supports wider aspect ratios without changing vertical framing",
      state: "partial",
    },
    {
      sourceId: "S006",
      label: "Native camera and world transforms render between simulation ticks",
      state: "partial",
    },
    {
      sourceId: "S007",
      label:
        "Deterministic checks compare the port with independent retail behavior at proven boundaries",
      state: "partial",
    },
    {
      sourceId: "S008",
      label:
        "The retail game modes are reachable and playable end to end on the shipping native path",
      state: "partial",
    },
  ],
  gears1: [
    {
      sourceId: "S001",
      label: "Exact Gears 1 revision boots and reaches gameplay through the retained recomp path",
      state: "verified",
    },
    {
      sourceId: "S002",
      label: "Gears 1 compatibility renderer produces bounded, retired, headless gameplay frames",
      state: "verified",
    },
    {
      sourceId: "S003",
      label: "Native RHI semantic stream represents and checks the observed Gears 1 frame boundary",
      state: "partial",
    },
    {
      sourceId: "S004",
      label: "Grounded native RHI operations replace retained execution with same-binary controls",
      state: "partial",
    },
    {
      sourceId: "S005",
      label:
        "Complete native RHI frontend bypasses title PM4 construction and compatibility reconstruction",
      state: "missing",
    },
    {
      sourceId: "S006",
      label: "Every Gears UE3 title passes an exact-revision compatibility gate",
      state: "missing",
    },
    {
      sourceId: "S007",
      label: "Native engine sustains the 5 ms / 200 fps renderer budget on representative gameplay",
      state: "missing",
    },
    {
      sourceId: "S008",
      label: "Public distribution provisions from a user-owned game image through `./run.sh`",
      state: "partial",
    },
  ],
  psxport: [
    {
      sourceId: "S001",
      label: "MIPS R3000A executables are translated into deterministic generated C",
      state: "verified",
    },
    {
      sourceId: "S002",
      label: "Native runtime owners provide GPU, SPU, GTE, MDEC, CD, XA/FMV, and BIOS services",
      state: "partial",
    },
    {
      sourceId: "S003",
      label:
        "Shipping differential infrastructure compares independent guest-state snapshots and frame boundaries",
      state: "verified",
    },
    {
      sourceId: "S004",
      label:
        "Game-owned native producers replace guest graphics while supporting widescreen and interpolation",
      state: "partial",
    },
    {
      sourceId: "S005",
      label: "Multiple title repositories consume the framework through narrow title-owned seams",
      state: "verified",
    },
  ],
  "recomp-x86": [
    {
      sourceId: "S001",
      label:
        "The translator emits C bodies and native dispatch metadata from x86-32 module exports",
      state: "verified",
    },
    {
      sourceId: "S002",
      label:
        "Unsupported instructions and invalid or empty inputs fail loudly instead of producing incomplete output",
      state: "verified",
    },
    {
      sourceId: "S003",
      label: "Generated output is tied to translator, input, and native-override revisions",
      state: "verified",
    },
    {
      sourceId: "S004",
      label:
        "Ghidra exports, pointer-table seeds, DLL thunks, and hosted analysis support feed the same translator",
      state: "verified",
    },
    {
      sourceId: "S005",
      label:
        "Port-specific loaders, schedulers, guest memory, and native overrides remain outside the shared translator",
      state: "verified",
    },
  ],
  lucent: [
    {
      sourceId: "S001",
      label:
        "Typed configuration and one channel-based logger provide portable process diagnostics",
      state: "verified",
    },
    {
      sourceId: "S002",
      label: "Applications resolve and create private OS-native user-data directories",
      state: "verified",
    },
    {
      sourceId: "S003",
      label:
        "A bounded local HTTP server owns request parsing, framing, concurrency, scope, and lifecycle",
      state: "verified",
    },
    {
      sourceId: "S004",
      label:
        "Streaming content identity and bounded ZIP discovery/extraction support safe player-owned imports",
      state: "verified",
    },
    {
      sourceId: "S005",
      label: "Platform-neutral multi-touch routing owns contact capture, zones, and cancellation",
      state: "verified",
    },
    {
      sourceId: "S006",
      label:
        "Android helpers stage user-selected content through private storage and persisted grants",
      state: "partial",
    },
    {
      sourceId: "S007",
      label: "HTTP responses stream bounded files without loading complete media into memory",
      state: "partial",
    },
  ],
  alchemy: [
    {
      sourceId: "S001",
      label: "IGB containers and the measured Xbox 360 and PS2 corpora can be opened and inspected",
      state: "verified",
    },
    {
      sourceId: "S002",
      label: "Mesh, texture, raster, and animation payloads decode into native semantic data",
      state: "partial",
    },
    {
      sourceId: "S003",
      label:
        "XMLB, FB/WAD, ARK class, font, and conversation tooling exposes reusable engine formats",
      state: "partial",
    },
    {
      sourceId: "S004",
      label:
        "Platform-neutral controller snapshots and an SDL3 backend support stable native devices",
      state: "partial",
    },
    {
      sourceId: "S005",
      label:
        "Existing standalone viewers and dump tools inspect measured assets without depending on a game port",
      state: "verified",
    },
  ],
  "port-assets": [
    {
      sourceId: "S001",
      label: "Generic keyboard and gamepad device indicators are available as original SVGs",
      state: "verified",
    },
    {
      sourceId: "S002",
      label:
        "A complete Xbox 360-style controller prompt family covers buttons, triggers, sticks, and directions",
      state: "verified",
    },
    {
      sourceId: "S003",
      label: "Label-neutral keyboard keycaps can display the consumer's actual binding",
      state: "verified",
    },
    {
      sourceId: "S004",
      label: "Authored touch-direction controls provide distinct up, down, left, and right prompts",
      state: "verified",
    },
    {
      sourceId: "S005",
      label:
        "Manifests and authoring checks prevent missing, stale, or indistinguishable glyphs, with target-background review required for legibility",
      state: "verified",
    },
  ],
  pinest: [
    {
      sourceId: "S1",
      label: "PiNest extension is ported and loads under pi",
      state: "verified",
    },
    {
      sourceId: "S2",
      label: "Session registry is private, owner-bound, and persisted to disk",
      state: "verified",
    },
    {
      sourceId: "S3",
      label: "Sessions survive a real host crash/restart and resume with full history",
      state: "partial",
    },
    {
      sourceId: "S4",
      label: "Explicit live harness reload adopts running sessions safely",
      state: "verified",
    },
    {
      sourceId: "S5b",
      label: "Hosted discovery and browser authentication provide zero-config distribution",
      state: "partial",
    },
    {
      sourceId: "S5",
      label: "GLM-5.3-Flash defaults to a one-million-token context with configured compaction",
      state: "verified",
    },
    {
      sourceId: "S6",
      label: "Flutter clients provide durable remote session control and release delivery",
      state: "partial",
    },
    {
      sourceId: "S7",
      label:
        "One owner is isolated through hardened authentication, protocol, discovery, and release boundaries",
      state: "partial",
    },
  ],
  "node-gtk-vte": [
    {
      sourceId: "S001",
      label:
        "Bun loads GTK 3, VTE 2.91, and GObject directly and can construct a native terminal window",
      state: "partial",
    },
    {
      sourceId: "S002",
      label: "Applications can feed terminal output and receive translated user input bytes",
      state: "partial",
    },
    {
      sourceId: "S003",
      label:
        "GTK window, container, notebook, label, button, menu, image, overlay, alignment, and CSS bindings support application composition",
      state: "partial",
    },
    {
      sourceId: "S004",
      label:
        "Helpers retain native strings and callbacks and release connected handlers explicitly",
      state: "partial",
    },
    {
      sourceId: "S005",
      label:
        "Automated controls verify the FFI surface, lifecycle helpers, and failure behavior on a real Linux runtime",
      state: "missing",
    },
  ],
  "re-harness": [
    {
      sourceId: "S001",
      label: "Project-agnostic skills are packaged under the global scope",
      state: "verified",
    },
    {
      sourceId: "S002",
      label: "Port architecture guidance is usable without the recomp stack",
      state: "verified",
    },
    {
      sourceId: "S003",
      label: "Reverse-engineering skills are grouped independently of recomp methodology",
      state: "verified",
    },
    {
      sourceId: "S004",
      label: "Static-recompiler-only skills are grouped under an explicit recomp scope",
      state: "verified",
    },
    {
      sourceId: "S005",
      label: "Reusable CLIs have canonical implementations and stable compatibility entry points",
      state: "verified",
    },
    {
      sourceId: "S006",
      label:
        "Codex, Claude, and generic agent homes converge instructions, skills, and tools through safe relative links",
      state: "verified",
    },
    {
      sourceId: "S007",
      label: "The shared tools and installer have positive and negative verification controls",
      state: "verified",
    },
    {
      sourceId: "S008",
      label:
        "Global project guidance requires every maintained project and catalogue to expose a complete stateful intended-feature inventory",
      state: "verified",
    },
  ],
  "wails-dbman": [
    {
      sourceId: "S001",
      label: "Users can add, edit, remove, persist, and test database connections",
      state: "partial",
    },
    {
      sourceId: "S002",
      label: "The explorer discovers SQL Server databases, tables, views, and stored procedures",
      state: "partial",
    },
    {
      sourceId: "S003",
      label:
        "Query tabs provide a Monaco editor, execution, multiple result sets, timing, and completion",
      state: "partial",
    },
    {
      sourceId: "S004",
      label:
        "Table, view, and procedure tabs expose data, schemas, definitions, paging, sorting, and filtering",
      state: "partial",
    },
    {
      sourceId: "S005",
      label: "PostgreSQL and MySQL provide feature-equivalent discovery and query behavior",
      state: "missing",
    },
    {
      sourceId: "S006",
      label:
        "Tabs, theme, explorer sizing, and global object search persist as a coherent desktop workspace",
      state: "partial",
    },
  ],
  "wails-cast": [
    {
      sourceId: "S001",
      label:
        "The desktop discovers Chromecast devices and controls play, pause, stop, seek, volume, and mute",
      state: "partial",
    },
    {
      sourceId: "S002",
      label:
        "Local files, remote URLs, HLS streams, track selection, transcoding, and cache reuse form one playback pipeline",
      state: "partial",
    },
    {
      sourceId: "S003",
      label:
        "Background downloads, extraction, translation, progress, cancellation, and resume preserve valid state",
      state: "partial",
    },
    {
      sourceId: "S004",
      label:
        "Embedded, nearby, external, translated, and burned-in subtitle workflows are available per episode",
      state: "partial",
    },
    {
      sourceId: "S005",
      label:
        "Library scanning, identification, organization, seasons, episodes, and torrent submission support media management",
      state: "partial",
    },
    {
      sourceId: "S006",
      label:
        "A token-protected advertised Remote API exposes library, playback, subtitle, translation, and settings operations",
      state: "partial",
    },
  ],
  "wails-cast-remote": [
    {
      sourceId: "S001",
      label:
        "The app discovers Wails Cast hosts over mDNS and supports manual authenticated connection",
      state: "partial",
    },
    {
      sourceId: "S002",
      label: "Users browse the remote library, refresh it, and submit arbitrary media URLs",
      state: "partial",
    },
    {
      sourceId: "S003",
      label: "Users select output device, video, audio, subtitle, and quality before playback",
      state: "partial",
    },
    {
      sourceId: "S004",
      label:
        "Now Playing provides live position, play, pause, stop, seek, volume, and mute controls",
      state: "partial",
    },
    {
      sourceId: "S005",
      label:
        "Subtitle translation, status, retranslation, and synced playback preferences work end to end",
      state: "partial",
    },
    {
      sourceId: "S006",
      label: "Android and iOS releases are qualified against the shipping desktop API",
      state: "missing",
    },
  ],
  "fedora-kde-steamdeck": [
    {
      sourceId: "S001",
      label:
        "Installation adds a Wayland session picker and Plasma shortcut for entering game mode",
      state: "partial",
    },
    {
      sourceId: "S002",
      label:
        "The selected session launches Steam Gamepad UI under fullscreen Gamescope and logs the run",
      state: "partial",
    },
    {
      sourceId: "S003",
      label: "Returning to desktop logs out through an available KDE or system session command",
      state: "partial",
    },
    {
      sourceId: "S004",
      label:
        "Installation and removal are documented, validated, and tested without leaving user files behind",
      state: "missing",
    },
  ],
} as const satisfies Record<string, readonly ProjectFeature[]>;

export type ProjectSlug = keyof typeof featuresByProject;

export function featuresFor(slug: ProjectSlug): readonly ProjectFeature[] {
  return featuresByProject[slug];
}
