// Generated by tools/sync_wasm_publications.py. Do not edit by hand.

export interface WasmPublication {
  sourceRepository: string;
  sourceCommit: string;
  sourceRunId: number;
}

const publications: Record<string, WasmPublication> = {
  benefactor: {
    sourceRepository: "SomeoneIsWorking/benefactor",
    sourceCommit: "9b66ca5110dd637e3b48c7d6c21e278a0e181621",
    sourceRunId: 34793537255,
  },
  "lf2-port": {
    sourceRepository: "SomeoneIsWorking/lf2-port",
    sourceCommit: "2bbd617b309737f9ca71ec8b5548ceebb029368f",
    sourceRunId: 35441971535,
  },
  xmen2: {
    sourceRepository: "SomeoneIsWorking/xmen2",
    sourceCommit: "8e0cabb21c4e3a097ce7ed79bf729783b2eaff59",
    sourceRunId: 35476098695,
  },
};

export function wasmPublicationFor(slug: string): WasmPublication | undefined {
  return publications[slug];
}
