// Generated by tools/sync_wasm_publications.py. Do not edit by hand.

export interface WasmPublication {
  sourceRepository: string;
  sourceCommit: string;
  sourceRunId: number;
}

const publications: Record<string, WasmPublication> = {
  benefactor: {
    sourceRepository: "SomeoneIsWorking/benefactor",
    sourceCommit: "9b66ca5110dd637e3b48c7d6c21e278a0e181621",
    sourceRunId: 34793537255,
  },
  "lf2-port": {
    sourceRepository: "SomeoneIsWorking/lf2-port",
    sourceCommit: "afdd30ba24bfdf6306ace2f33a8cbdd822a94277",
    sourceRunId: 35341381565,
  },
  xmen2: {
    sourceRepository: "SomeoneIsWorking/xmen2",
    sourceCommit: "295fba41a9497579239da038837c210f8b31f9c3",
    sourceRunId: 35439280148,
  },
};

export function wasmPublicationFor(slug: string): WasmPublication | undefined {
  return publications[slug];
}
