// Generated by tools/sync_wasm_publications.py. Do not edit by hand.

export interface WasmPublication {
  sourceRepository: string;
  sourceCommit: string;
  sourceRunId: number;
}

const publications: Record<string, WasmPublication> = {
  benefactor: {
    sourceRepository: "SomeoneIsWorking/benefactor",
    sourceCommit: "9b66ca5110dd637e3b48c7d6c21e278a0e181621",
    sourceRunId: 34793537255,
  },
  "lf2-port": {
    sourceRepository: "SomeoneIsWorking/lf2-port",
    sourceCommit: "2bbd617b309737f9ca71ec8b5548ceebb029368f",
    sourceRunId: 35441971535,
  },
  xmen2: {
    sourceRepository: "SomeoneIsWorking/xmen2",
    sourceCommit: "8c9f0c82cdf8dfd7f44a019c784a93ec9b2c8812",
    sourceRunId: 35980135658,
  },
};

export function wasmPublicationFor(slug: string): WasmPublication | undefined {
  return publications[slug];
}
